name: 'GH Action Check Directory Changes'
description:
  'Check if specific directories have changed in a GitHub repository.'
author: 'mattyfours'

inputs:
  directories:
    description: 'Comma-separated list of directories to check for changes.'
    required: true

outputs:
  has-changed:
    description: 'Boolean indicating if the specified directories have changed.'

runs:
  using: 'node20'
  main: 'dist/index.js'
